### ISSUE TITLE
shavar is not sending sub chunks for old chunk data

### ISSUE THREAD

**Issue by monicachew** [mozilla-services/shavar#21]
Chunk data has always been indexed by timestamp. The prototype version of shavar sent a pleasereset command in response to a chunk number that was less than the timestamp of the current chunk.

This version of shavar leaves old chunks in place and just adds the new chunk. This means that blocklist updates that *remove* stuff from the blocklist have no effect. It also means that the blocklist always keeps taking more space on the Firefox side.

There needs to be be logic to remove old chunks if the chunk number doesn't match what's in AWS. I wrote a test case in git@github.com:monicachew/shavar-test.git to demonstrate this. Run "run_with_chunk_data.txt" to see that the server response just adds the new chunk.

@rfk @rtilder this is a serious bug.

**Comment by rtilder** [comment]
I'm a little confused by your first paragraph.  According to issue #1, we should never issue a pleasereset.  Has this situation changed?

As for the bug you mention: shavar serves data for a given sblist from a single S3 file specified in its config file.  shavar doesn't keep track of an sblist's data history.  The sblist creation tool is responsible for generating sub chunks and including them in the data file it uploads to S3.  Is the sblist creation tool not doing that?

**Comment by monicachew** [comment]
We should still not be sending pleasereset, though we may have to as a temporary workaround to this issue.

The sblist creation tool is stateless and does not know what chunk numbers have already been generated. In fact, it can't generated sub (or adddel) chunks, because different users may have received different add chunks, so the server needs to do this.

**Comment by monicachew** [comment]
It looks like https://github.com/mozilla-services/shavar/blob/master/shavar/parse.py#L75 parses the chunks that the user claims to have, but that information is not used anywhere.

It seems like _populate_chunks could use claimed chunks in addition to the file on S3 to send the right subtractions.

https://github.com/mozilla-services/shavar/blob/e38d654761d8a1882038670e3f4bf187b6e31d0e/shavar/sources.py#L88

**Comment by monicachew** [comment]
We still aren't using redirects as the spec defines, right? And sending all chunks inline?

I'm going to write a node server to test whether Firefox processes adddels correctly when sent inline with add chunk data.

**Comment by monicachew** [comment]
@sjhworkman, @dougt fyi

**Comment by monicachew** [comment]
The good news is that we can send adddels inline to fix up clients. Even better, we can send this as a range so there's not much need to parse existing chunk data: the server just sends

ad:1-<current chunk number - 1>

and the clients should delete previous chunks. I've added a test node server to https://github.com/monicachew/shavar-test and response_with_adddel_range.out to illustrate this.

**Comment by monicachew** [comment]
And now that I know that a range works, we can fix it in shavar-list-creation, which I think can just add the ad:1-chunk_number line before the chunk data starts.

**Comment by monicachew** [comment]
Filed https://github.com/mozilla-services/shavar-list-creation/issues/8

**Comment by monicachew** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1127603 to get the fix deployed.

**Comment by monicachew** [comment]
See #23

**Comment by monicachew** [comment]
See #27. #23 was a non-starter.

**Comment by fmarier** [comment]
I believe this bug was fixed a while back in production.
