### ISSUE TITLE
refresh interval is still broken

### ISSUE THREAD

**Issue by monicachew** [mozilla-services/shavar#22]
From ckolos in https://bugzilla.mozilla.org/show_bug.cgi?id=1127603#c3:

> To be sure, I logged into the existing server and hup'd the shavar process. On restart, the timestamp has been updated. It looks like the periodic refresh of the list from the app itself isn't happening.

**Comment by ckolos** [comment]
Looks like this is my error.
2 things to note:

Changes are polled for every 10 minutes
Changes are only polled for on a per request basis.
