### ISSUE TITLE
shavar is not sending adddel directives

### ISSUE THREAD

**Issue by monicachew** [mozilla-services/shavar#23]
Even though the adddel directive was added in https://github.com/mozilla-services/shavar-list-creation/commit/d992d1a442df16e9d7f1e12301358e32adce2e50, shavar isn't passing it along.

The logic for parsing the file from s3 ignores ad: lines.
https://github.com/mozilla-services/shavar/blob/master/shavar/parse.py#L124

Either this function has to change to insert_adddel when necessary, or _populate_chunks needs to go ahead and add the adddel range:
https://github.com/mozilla-services/shavar/blob/e38d654761d8a1882038670e3f4bf187b6e31d0e/shavar/sources.py#L33

@rfk @rtilder @sjhworkman

**Comment by monicachew** [comment]
This is confirmed by comparing https://bug1127603.bugzilla.mozilla.org/attachment.cgi?id=8557263 (what's currently on s3) to the output of the current endpoint (https://github.com/monicachew/shavar-test), which is missing the "ad:" line.

**Comment by rtilder** [comment]
It doesn't support that syntax because it wasn't part of the original file format.  Only normal adds and subs were supported because that's what was required.  It should definitely be a requirement for a future release but I think we'll address that when we switch away from the current single file per list publishing format.

**Comment by monicachew** [comment]
Revocations are definitely a requirement. This bug (or mismatch in expectations of who is computing deltas, or whatever you'd like to call it) was not exposed until we had enough users on tracking protection that I wanted to push a blocklist update.

This is a major implementation difference with the prototype server, which revoked through pleasereset. Generating subs at list creation time does not make sense: sending subs requires sending chunk data, and that's going to potentially be different for each client.

I can work on adding adddel support, but my environment is not setup to do so. How do you do local development on shavar?

**Comment by monicachew** [comment]
I have to apologize. In my local testing sending a blanket adddel range seemed to work. However I just happened to have a lot of memory on my test machine :( Thus, intermittent failures and https://bugzilla.mozilla.org/show_bug.cgi?id=1134858.

This should be a comma separated list of adddel chunks rather than a range.
