### ISSUE TITLE
Support non-delta publishing

### ISSUE THREAD

**Issue by monicachew** [mozilla-services/shavar#27]
If non-delta-publishing is true, then parse existing chunks from client and send back comma-separated adddel chunks for them.

**Comment by monicachew** [comment]
@rtilder , it's coming up on March 13 which is the completion date we set when doing the postmortem a couple weeks ago -- is that still feasible?

**Comment by rtilder** [comment]
Amusingly, I realized only yesterday that I'd said mid March and not mid April like I'd meant to.  The dangers of extended periods of too little sleep.  Either way, I banged out the minimum necessary changes last night and reviewed it this morning.  PR #30 should fix it.

**Comment by rtilder** [comment]
Closing because all lists will be published as deltas shortly.
