### ISSUE TITLE
Write documentation on how to setup and run shavar locally

### ISSUE THREAD

**Issue by monicachew** [mozilla-services/shavar#29]
This is probably obvious to egg/pyramid experts but I've gotten this question from @fmarier and one other person (decoder) and didn't know the answer.

**Comment by fmarier** [comment]
@rtilder what command line do you use in dev to startup the shavar server?

**Comment by fmarier** [comment]
Available here: https://github.com/rtilder/shavar/blob/better-docs/README.md

**Comment by rtilder** [comment]
Merged with PR #45
