### ISSUE TITLE
gethash completions do not work

### ISSUE THREAD

**Issue by monicachew** [mozilla-services/shavar#32]
No response from endpoint.

![screen shot 2015-03-26 at 6 14 30 pm](https://cloud.githubusercontent.com/assets/2326155/6860370/6a739e9e-d3e4-11e4-94b9-842d4a690a67.png)

See also https://bugzilla.mozilla.org/show_bug.cgi?id=1148158

@rtilder @rfk @fmarier

**Comment by rtilder** [comment]
From the production logs: ParseError('Improbably small or large gethash header size: 3',)

That means that the header portion of the POST body is only 3 characters long(most probably the string "4:4" or "4:8").

From our discussions last year, the minimum size of a call to gethash would be four hash prefixes: the prefix for the actual URL that's being looked up and three other randomly generated prefixes(essentially 3 * 4-random-bytes).  The error from the logs indicates that one or fewer random prefixes are being included in the request.  Do we need to revisit what the safe minimum gethash POST body should be?

Definitely at least one service side bug: at least a 500 response should have been included but probably a 400 to meet the protocol spec.

**Comment by monicachew** [comment]
I think a request of 1 hash prefix is acceptable. We will investigate why less noise is being sent, but keep in mind that the number of gethash noise additions is configurable, and we don't want to penalize people who set it to 0.

**Comment by rtilder** [comment]
Fixed in PR #34 and deployed with revision 0.6.2 that was deployed to production the week of June 15, 2015.
