### ISSUE TITLE
Hosting two test resources

### ISSUE THREAD

**Issue by fmarier** [mozilla-services/shavar#43]
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1182876, I want to hard-code test URLs that will be blocked by tracking protection.

I suggest:

* https://tracking.services.mozilla.com/firefox/track.js
* https://tracking.services.mozilla.com/firefox/whitelisted.js

And both of these would be static files containing the following text:

    /* not actually a tracker! */

@rtilder does that look reasonable or would you rather have slightly different URLs?

**Comment by fmarier** [comment]
On the client, I would do the following:

* blacklist `tracking.services.mozilla.com/firefox/`
* whitelist `itisatrap.org/?r=tracking.services.mozilla.com/firefox/whitelisted.js`

which would allow [itisatrap.org/firefox/its-a-tracker.html](https://bugzilla.mozilla.org/show_bug.cgi?id=1149825) to pull in `whitelisted.js` but not `track.js`.

**Comment by ckolos** [comment]
To do this we'll need to:
* add the blacklisted url in the list-generation code
* add the whitelisted url to the whitelist
* config nginx to serve the static resources
* include the static resources in the puppet code used to provision the server

Looking through this, I'm not sure what exactly is being tested here. The server? The client? The blocklist? These changes would seem to only affect the blocklist and/or the client.

**Comment by fmarier** [comment]
>- add the blacklisted url in the list-generation code
> - add the whitelisted url to the whitelist

These are not required because they will be [hardcoded in the client](https://bugzilla.mozilla.org/show_bug.cgi?id=1182876) so that we can test this without network access.

It's only for testing the client, not the server or the list.

**Comment by fmarier** [comment]
This is a dependency of the client test page: https://bugzilla.mozilla.org/show_bug.cgi?id=1149825

@ckolos Is there anything else you need from me or is it a straightforward config change?

**Comment by fmarier** [comment]
Actually, I made a mistake in https://github.com/mozilla-services/shavar/issues/43#issuecomment-120887234 and the format isn't quite right. The whitelist is not going to be that granular. We'll need a different origin to host the whitelisted resource.

I'll come up with something better and file a bug with IT instead. Sorry for the noise.
