### ISSUE TITLE
implement the list API call

### ISSUE THREAD

**Issue by fmarier** [mozilla-services/shavar#44]
Not a high priority of course, but it would be nice (for debugging purposes for example) if shavar would implement the [`list` endpoint](https://developers.google.com/safe-browsing/developers_guide_v2#HTTPRequestForList).

I wrote a [small tool](https://github.com/fmarier/safebrowsing-tools/blob/master/get-lists.py) to easily query what's available on a Safe Browsing server.

**Comment by fmarier** [comment]
In the meantime, we should ideally return a `501 Not Implemented` when receiving a POST on `/list`.

**Comment by ckolos** [comment]
`curl https://tracking.services.mozilla.com/list` should tell you what's available on the server.

**Comment by rtilder** [comment]
That API endpoint has been implemented for quite a while.  Are you having trouble with something in particular?

**Comment by fmarier** [comment]
Oh, I hadn't tried a `GET` :)

The spec says that it should be a `POST`. Perhaps we should add that to be in line with the Google server?

I don't see any harm in keeping GET if you're using it anywhere.

**Comment by rtilder** [comment]
I swear that spec was written by teenage girls.  Why would it be a POST?  It doesn't take any input.  I'll fix.

**Comment by fmarier** [comment]
This works in production.
