### ISSUE TITLE
Incorrect usage of str.split()

### ISSUE THREAD

**Issue by palant** [mozilla-services/shavar#64]
The codebase contains statements like the following:

    lname, chunklist = line.split(";", 2)

This particular example can be found [here](https://github.com/mozilla-services/shavar/blob/45b9d87/shavar/parse.py#L31). Whoever wrote this seems to think that the second parameter to `str.split()` indicates the number of resulting string parts, like in JavaScript. However, in Python it's the [maximum number of splits](https://docs.python.org/2/library/stdtypes.html#str.split), so it should be `line.split(";", 1)`.

**Comment by rtilder** [comment]
Lots of instances.  Fixed.
