### ISSUE TITLE
Uncaught exception if a request line doesn't contain a semicolon 

### ISSUE THREAD

**Issue by palant** [mozilla-services/shavar#65]
[This line](https://github.com/mozilla-services/shavar/blob/45b9d87/shavar/parse.py#L31) throws "ValueError: need more than 1 value to unpack" if the request contains a non-empty line without a semicolon. I confirmed that the server responds with "502 Bad Gateway" in that case.

**Comment by rtilder** [comment]
I noticed the same thing last week and had a patch queued for commit.  Thanks.
