### ISSUE TITLE
Dead code: variable claims in shavar.parse.parse_downloads()

### ISSUE THREAD

**Issue by palant** [mozilla-services/shavar#66]
The logic in `shavar.parse.parse_downloads()` is somewhat obfuscated by the variable `claims` that is being initialized, then "extended" by `claim` (which is always an empty array because nothing is ever added to it) and then thrown away. Unless I'm entirely mistaken this is dead code.

**Comment by rtilder** [comment]
Yup.  Totally dead code.  The result of some poor cherry picking on my part.
