### ISSUE TITLE
Add shavar block- and allow-lists for Flash blocking

### ISSUE THREAD

**Issue by groovecoder** [mozilla-services/shavar#92]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1314094 and particularly https://bugzilla.mozilla.org/show_bug.cgi?id=1314094#c21 ...
```
block-flash-digest256 (flash.txt)
except-flash-digest256 (flashexceptions.txt)
allow-flashallow-digest256 (flashallow.txt)
except-flashallow-digest256 (flashallowexceptions.txt)
block-flashsubdoc-digest256 (flashsubdoc.txt)
except-flashsubdoc-digest256 (flashsubdocexceptions.txt)
```

### Stage
1. [x] Add files to https://github.com/mozilla-services/shavar-plugin-blocklist
2. [x] Add the lists to https://github.com/mozilla-services/shavar-list-creation and https://github.com/mozilla-services/shavar-list-creation-config
3. [x] Add the lists to https://github.com/mozilla-services/shavar-server-list-config

### Production
1. [x] Add files to https://github.com/mozilla-services/shavar-plugin-blocklist
2. [x] Add the lists to https://github.com/mozilla-services/shavar-list-creation and https://github.com/mozilla-services/shavar-list-creation-config
3. [x] Add the lists to https://github.com/mozilla-services/shavar-server-list-config

**Comment by groovecoder** [comment]
Added the new flash lists to `shavar-list-creation` and `stage.ini` on `shavar-list-creation-config`. We should be able to merge those and see the script put new list files onto the stage server. Will start on that tomorrow.

**Comment by groovecoder** [comment]
@ckolos check my math here ... if we merge all 3 of these PRs and bounce the shavar stage server, it should start serving the new flash lists, right?

https://github.com/mozilla-services/shavar-list-creation/pull/44
https://github.com/mozilla-services/shavar-list-creation-config/pull/15
https://github.com/mozilla-services/shavar-server-list-config/pull/3

**Comment by ckolos** [comment]
that looks correct. I think that order is correct as well. I would ask that you stagger the merge to the list-creation-config +30mins or so after the merge to list-creation, but other than that lgtm.

**Comment by groovecoder** [comment]
Merged `shavar-list-creation` and set myself a 30m timer.

**Comment by rbillings** [comment]
Verified new flashblock lists: browser shield display & local safebrowsing files & file sizes.

**Comment by groovecoder** [comment]
Thanks @rbillings.

@ckolos - can you verify that 0.9 is in production? (E.g., could see if [the 0.9 line is in the CHANGES.txt file](https://github.com/mozilla-services/shavar/commit/141e7f3110af2e59a26d9eaa7946e5873ee16cb7)) If it is, we should be able to push these flash block lists to production by following the remaining steps in https://github.com/mozilla-services/shavar/issues/92#issue-210864498

**Comment by ckolos** [comment]
prod is 0.7 
{"commit":"6b5ffd3a78da793e3830faf913a99293b07e0ea5","version":"0.7","source":"https://github.com/mozilla-services/shavar.git"}

stage is 0.9
{"commit":"141e7f3110af2e59a26d9eaa7946e5873ee16cb7","version":"0.9","source":"https://github.com/mozilla-services/shavar","build":"https://circleci.com/gh/mozilla-services/shavar/82"}

If we're all okay with another prod release being needed to get dynamic list configuration, then I can deploy 0.9 as-is to prod. It's a step in the right direction, even if it's not 100% where we wanted to be.

**Comment by groovecoder** [comment]
I'm good with it, yeah. I'm on-hand all day today too - no meetings! @rbillings - would you be able to run thru the regular shavar test plan (i.e., without flash-blocking) first so we can verify 0.9 is good before we add the flash-blocking lists to it?

**Comment by groovecoder** [comment]
So, next steps:

1. Merge https://github.com/mozilla-services/shavar-list-creation-config/pull/16 and make sure [ShavarListCreationProd](https://deploy.mozaws.net/view/Shavar%20Prod/job/ShavarListCreationProd/) is publishing the new flash-blocking lists to the expected prod S3 bucket.
2. Merge https://github.com/mozilla-services/shavar-server-list-config/pull/5 and restart prod shavar servers to start serving the new flash-blocking lists.

**Comment by groovecoder** [comment]
Production shavar is serving the new flash-blocking lists.
